config/routes.rb
Rails.application.routes.draw do
  resources :apps, param: :token, only: [:index, :show, :create, :destroy] do
    resources :chats, param: :chat_id, only: [:index, :show, :create, :destroy] do
      resources :messages, only: [:index, :show, :create, :destroy]
        # collection do
        #   post 'search', to: 'messages#search'
        # end
      # end
    end
  end
root "apps#index"
end

app/models/app.rb
class App < ApplicationRecord
    before_validation :generate_token, on: :create

    has_many :chats, dependent: :destroy, counter_cache: true
    validates :token, presence: true, uniqueness: true
    validates :name, presence: true

    def generate_token
        self.token = loop do
        random_token = Random.urlsafe_base64(nil, false)
        break random_token unless App.exists?(token: random_token)
        end
        self.token=token
    end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat.rb
class Chat < ApplicationRecord
  # Associations
  before_validation :set_chat_number, on: :create
  belongs_to :app ,counter_cache: true
  has_many :messages, dependent: :destroy
  
  # Validations
  validates :app, presence: true

  # # Methods
  def set_chat_number
    if self.app
      self.id = self.app.chats.count + 1
    end
  end
end

app/models/concerns/searchable.rb
module Searchable
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  index_name 'messages'

  settings do
    mappings dynamic: false do
      indexes :body, type: 'text'
    end
  end

  def self.search(query)
    __elasticsearch__.search(
      {
        body: {
          query: {
            match: {
              body: query
            }
          }
        }
      }
    )
  end
end

app/models/message.rb
class Message < ApplicationRecord
  # include Elasticsearch::Model
  # include Elasticsearch::Model::Callbacks
  # include Searchable
  belongs_to :chat, counter_cache: true

  # Validations
  validates :body, presence: true
  #validates :number, presence: true, uniqueness: { scope: :chat_id }
    
  
  # def self.search(query)
  #   __elasticsearch__.search(
  #     {
  #       query: {
  #         multi_match: {
  #           query: query,
  #           fields: ['body']
  #           }
  #         }
  #       }
  #     ).records
  #   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  protect_from_forgery with: :null_session
  allow_browser versions: :modern
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController

  # GET /apps or /apps.json
  def index
    @apps = App.all
    render json: @apps
  end

  # GET /apps/:token or /apps/:token.json
  def show
    @app = App.find_by(token: params[:token])
    render json: @app
  end

  # GET /apps/new
  def new
    @app = App.new
  end

  # GET /apps/1/edit
  def edit
  end

  # POST /apps or /apps.json
  def create
    Rails.logger.debug("App Params: #{app_params.inspect}")
    CreateAppJob.perform_async(app_params[:token], app_params[:name])
    render json: app_params[:name], status: :created
  end

  private

  def app_params
    params.permit(:name)
  end
  
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  # before_action :set_application
  #before_action :set_chat, only: %i[ show edit update destroy ]

  # GET /apps/:token/chats
  def index
    @app = App.find_by("token": params[:app_token])
    if @app.nil?
      # Handle the case where the app is not found
      render json: { error: 'App not found' }, status: :not_found
    else
      @chats = @app.chats # Get all chats for the found app
      render json: @chats
    end
  end

  # GET /chats/1 or /chats/1.json
  def show
    @app = App.find_by("token": params[:app_token])
    @chat = @app.chats.find_by!(id: params[:chat_id])
    if @chat.nil?
      Rails.logger.debug("Chat not found with ID: #{params[:chat_id]} in app with token: #{params[:app_token]}")
      render json: { error: 'Chat not found' }, status: :not_found
      return
    end
    render json: @chat
  end

  # GET /chats/new
  def new
    @chat = @app.chats.build
  end

  # POST /chats or /chats.json
  def create
    @app = App.find_by!("token": params[:app_token])

    chat_number = next_chat_number(@app.token)
    $redis.set("#{params[:app_token]}_#{chat_number}_next_message_num", 1)
    CreateChatJob.perform_async(params[:app_token], chat_number)

    render json: {number: chat_number, messages_count: 0}, status: :created
    
  end

  def destroy
    @app = App.find_by!(token: params[:app_token])
    chat = @app.chats.find_by!(id: params[:id])
    if chat.destroy
      render json: { message: 'Chat successfully deleted' }, status: :ok
    else
      render json: { error: 'Failed to delete chat' }, status: :unprocessable_entity
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    # Only allow a list of trusted parameters through.
    def chat_params
      params.permit(:number)
    end

    def next_chat_number(app_token)
      redis_key = "#{app_token}_next_chat_number"
      $redis_lock.lock(redis_key, 2000) do
        current_number = $redis.get(redis_key).to_i
        next_number = current_number + 1
        $redis.set(redis_key, next_number)
        puts "NEXT_NUMBER: #{next_number}"
        return next_number
      end
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[ show edit update destroy ]

  # GET /messages or /messages.json
  def index
    @app = App.find_by!(token: params[:app_token])
    @chat = @app.chats.find_by!(id: params[:chat_chat_id]) 
    @messages = @chat.messages
    render json: @messages, :except=> [:id, :chat_chat_id], status: :created
  end

  # GET /messages/1 or /messages/1.json
  def show
    @app = App.find_by!(token: params[:app_token])
    @chat = @app.chats.find_by!(id: params[:chat_chat_id]) 
    @message = @chat.messages.find(id: params[:id])
    render json: @message, :except=> [:number, :chat_chat_id], status: :created
  end

  # POST /messages or /messages.json
  def create
    @app = App.find_by!(token: params[:app_token])
    next_mesg_num = next_message_number(params[:app_token], params[:chat_chat_id])
    puts "Before createing message"
    CreateMessageJob.perform_async(params[:app_token], params[:chat_chat_id], next_mesg_num, message_params[:body])
    render json: {number: next_mesg_num, message: params[:body]}, :except=> [:id, :chat_chat_id], status: :created
  end

  def destroy
    if @message.destroy
      render json: { message: 'Message deleted successfully' }, status: :ok
    else
      render json: { error: 'Failed to delete message' }, status: :unprocessable_entity
    end
  end

  # def search
  #   if params[:q].present?
  #     puts "Query: #{params[:q]}"
  #     @messages = Message.search(params[:q]).records.to_a
  #     puts "Search results: #{@messages}"
  #   else
  #     @messages = Message.all
  #   end
  #   render json: @messages.as_json(except: [:id])
  # end
  
  def search
    # @result = Message.search(params[:message])
    # render json: @result, :except=> [:id, :chat_id], status: :ok
    query = params[:query]
    if query.present?
      @result = Message.search(query) # Adjust this line based on your Elasticsearch setup
      render json: @result, except: [:id, :chat_id], status: :ok
    else
      render json: { error: 'Query parameter missing' }, status: :bad_request
    end
  end


  private

  def search_params
    params.permit(:query, :q)
  end
    # Use callbacks to share common setup or constraints between actions.
  def set_message
    @message = Message.where(chat_id: params[:chat_id])
  end

  # Only allow a list of trusted parameters through.
  def message_params
    params.permit(:body, :app_token ,:chat_id)
  end

  def next_message_number(app_token,chat_id)
    redis_key = "#{app_token}_#{chat_id}_next_msg_num"
    $redis_lock.lock(redis_key, 2000) do
      current_number = $redis.get(redis_key).to_i
      next_number = current_number + 1
      $redis.set(redis_key, next_number)
      return next_number
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/create_chats_helper.rb
module CreateChatsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/applications/create.html.erb
<h1>Applications#create</h1>
<p>Find me in app/views/applications/create.html.erb</p>

app/views/applications/destroy.html.erb
<h1>Applications#destroy</h1>
<p>Find me in app/views/applications/destroy.html.erb</p>

app/views/applications/edit.html.erb
<h1>Applications#edit</h1>
<p>Find me in app/views/applications/edit.html.erb</p>

app/views/applications/index.html.erb
<h1>Applications#index</h1>
<p>Find me in app/views/applications/index.html.erb</p>

app/views/applications/new.html.erb
<h1>Applications#new</h1>
<p>Find me in app/views/applications/new.html.erb</p>

app/views/applications/show.html.erb
<h1>Applications#show</h1>
<p>Find me in app/views/applications/show.html.erb</p>

app/views/applications/update.html.erb
<h1>Applications#update</h1>
<p>Find me in app/views/applications/update.html.erb</p>

app/views/apps/_app.html.erb
<div id="<%= dom_id app %>">
  <p>
    <strong>Name:</strong>
    <%= app.name %>
  </p>

  <p>
    <strong>Chats count:</strong>
    <%= app.chats_count %>
  </p>

</div>

app/views/apps/_form.html.erb
<%= form_with(model: app) do |form| %>
  <% if app.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(app.errors.count, "error") %> prohibited this app from being saved:</h2>

      <ul>
        <% app.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :chats_count, style: "display: block" %>
    <%= form.number_field :chats_count %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/apps/edit.html.erb
<% content_for :title, "Editing app" %>

<h1>Editing app</h1>

<%= render "form", app: @app %>

<br>

<div>
  <%= link_to "Show this app", @app %> |
  <%= link_to "Back to apps", apps_path %>
</div>

app/views/apps/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Apps" %>

<h1>Apps</h1>

<div id="apps">
  <% @apps.each do |app| %>
    <%= render app %>
    <p>
      <%= link_to "Show this app", app %>
    </p>
  <% end %>
</div>

<%= link_to "New app", new_app_path %>

app/views/apps/new.html.erb
<% content_for :title, "New app" %>

<h1>New app</h1>

<%= render "form", app: @app %>

<br>

<div>
  <%= link_to "Back to apps", apps_path %>
</div>

app/views/apps/show.html.erb
<p style="color: green"><%= notice %></p>

<% if @app %>
  <%= render @app %>
  <div>
    <%= link_to "Edit this app", edit_app_path(@app) %> |
    <%= link_to "Back", apps_path %>
  </div>
<% else %>
  <p>App not found</p>
<% end %>

app/views/chats/create.html.erb
<h1>Chats#create</h1>
<p>Find me in app/views/chats/create.html.erb</p>

app/views/chats/destroy.html.erb
<h1>Chats#destroy</h1>
<p>Find me in app/views/chats/destroy.html.erb</p>

app/views/chats/edit.html.erb
<h1>Chats#edit</h1>
<p>Find me in app/views/chats/edit.html.erb</p>

app/views/chats/index.html.erb
<h1>Chats#index</h1>
<p>Find me in app/views/chats/index.html.erb</p>

app/views/chats/new.html.erb
<h1>Chats#new</h1>
<p>Find me in app/views/chats/new.html.erb</p>

app/views/chats/show.html.erb
<h1>Chats#show</h1>
<p>Find me in app/views/chats/show.html.erb</p>

app/views/chats/update.html.erb
<h1>Chats#update</h1>
<p>Find me in app/views/chats/update.html.erb</p>

app/views/create_chats/_create_chat.html.erb
<div id="<%= dom_id create_chat %>">
  <p>
    <strong>Number:</strong>
    <%= create_chat.number %>
  </p>

  <p>
    <strong>Application:</strong>
    <%= create_chat.application_id %>
  </p>

  <p>
    <strong>Messages count:</strong>
    <%= create_chat.messages_count %>
  </p>

</div>

app/views/create_chats/_form.html.erb
<%= form_with(model: create_chat) do |form| %>
  <% if create_chat.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(create_chat.errors.count, "error") %> prohibited this create_chat from being saved:</h2>

      <ul>
        <% create_chat.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :number, style: "display: block" %>
    <%= form.number_field :number %>
  </div>

  <div>
    <%= form.label :application_id, style: "display: block" %>
    <%= form.text_field :application_id %>
  </div>

  <div>
    <%= form.label :messages_count, style: "display: block" %>
    <%= form.number_field :messages_count %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/create_chats/edit.html.erb
<% content_for :title, "Editing create chat" %>

<h1>Editing create chat</h1>

<%= render "form", create_chat: @create_chat %>

<br>

<div>
  <%= link_to "Show this create chat", @create_chat %> |
  <%= link_to "Back to create chats", create_chats_path %>
</div>

app/views/create_chats/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Create chats" %>

<h1>Create chats</h1>

<div id="create_chats">
  <% @create_chats.each do |create_chat| %>
    <%= render create_chat %>
    <p>
      <%= link_to "Show this create chat", create_chat %>
    </p>
  <% end %>
</div>

<%= link_to "New create chat", new_create_chat_path %>

app/views/create_chats/new.html.erb
<!-- app/views/chats/new.html.erb -->
<% content_for :title, "New Chat" %>

<h1>New Chat</h1>

<%= form_with(model: [@app, @chat], local: true) do |form| %>
  <!-- No need for number field as it is auto-assigned -->
  <div class="actions">
    <%= form.submit 'Create Chat' %>
  </div>
<% end %>

<br>

<div>
  <%= link_to "Back to Application", @app %>
</div>

app/views/create_chats/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @create_chat %>

<div>
  <%= link_to "Edit this create chat", edit_create_chat_path(@create_chat) %> |
  <%= link_to "Back to create chats", create_chats_path %>

  <%= button_to "Destroy this create chat", @create_chat, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Chat Apps V6" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: message) do |form| %>
  <% if message.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :number, style: "display: block" %>
    <%= form.number_field :number %>
  </div>

  <div>
    <%= form.label :chat_id, style: "display: block" %>
    <%= form.text_field :chat_id %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/messages/_message.html.erb
<div id="<%= dom_id message %>">
  <p>
    <strong>Number:</strong>
    <%= message.number %>
  </p>

  <p>
    <strong>Chat:</strong>
    <%= message.chat_id %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= message.body %>
  </p>

</div>

app/views/messages/create.html.erb
<h1>Messages#create</h1>
<p>Find me in app/views/messages/create.html.erb</p>

app/views/messages/destroy.html.erb
<h1>Messages#destroy</h1>
<p>Find me in app/views/messages/destroy.html.erb</p>

app/views/messages/edit.html.erb
<% content_for :title, "Editing message" %>

<h1>Editing message</h1>

<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Show this message", @message %> |
  <%= link_to "Back to messages", messages_path %>
</div>

app/views/messages/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Messages" %>

<h1>Messages</h1>

<div id="messages">
  <% @messages.each do |message| %>
    <%= render message %>
    <p>
      <%= link_to "Show this message", message %>
    </p>
  <% end %>
</div>

<%= link_to "New message", new_message_path %>

app/views/messages/new.html.erb
<% content_for :title, "New message" %>

<h1>New message</h1>

<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Back to messages", messages_path %>
</div>

app/views/messages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @message %>

<div>
  <%= link_to "Edit this message", edit_message_path(@message) %> |
  <%= link_to "Back to messages", messages_path %>

  <%= button_to "Destroy this message", @message, method: :delete %>
</div>

app/views/messages/update.html.erb
<h1>Messages#update</h1>
<p>Find me in app/views/messages/update.html.erb</p>